depends "application_javascript", "~> 1.0.0"
depends "tar", "~> 2.2.0"
description ""
issues_url ""
long_description ""
maintainer ""
maintainer_email ""
name "node-mysql-crud-app"
source_url ""
version "0.0.1"
